services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: "redis-server --requirepass ${REDIS_PASS} --port 6379"
    restart: always
  db:
    build:
      context: .
      dockerfile: "db.Dockerfile"
    restart: always
    ports:
      - "2999:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}